spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot


kafka:
  topic:
    roles: roles
